apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-shop-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-shop-ui
  template:
    metadata:
      labels:
        app: retail-shop-ui
    spec:
      containers:
        - name: retail-shop-ui
          image: gpalve/retail-shop-ui:latest
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: retail-shop-ui
spec:
  selector:
    app: retail-shop-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
